Repository openframeworks/openFrameworks, pull requests merged in 2024-08, with the labels that each got.

#8067 Emscripten 3.1.65 fix
  addons/ofxEmscripten/src/ofxAppEmscriptenWindow.cpp
  addons/ofxEmscripten/src/ofxAppEmscriptenWindow.h
Labels: emscripten

#4970 OpenGL ES 3.0 for iOS Renderer
  addons/ofxiOS/src/gl/EAGLKView.m
  addons/ofxiOS/src/gl/EAGLView.h
  addons/ofxiOS/src/gl/EAGLView.m
  addons/ofxiOS/src/gl/ES3Renderer.h
  addons/ofxiOS/src/gl/ES3Renderer.m
  addons/ofxiOS/src/ofxtvOS.h
  examples/ios/GLKit/src/main.mm
  examples/ios/iosES3ShaderExample/bin/data/shaders/noise.frag
  examples/ios/iosES3ShaderExample/bin/data/shaders/noise.vert
  examples/ios/iosES3ShaderExample/bin/data/type/verdana.ttf
  examples/ios/iosES3ShaderExample/src/main.mm
  examples/ios/iosES3ShaderExample/src/ofApp.h
  examples/ios/iosES3ShaderExample/src/ofApp.mm
  examples/tvOS/ofBoxExample/src/main.mm
  libs/openFrameworks/gl/ofGLUtils.cpp
  libs/openFrameworks/gl/ofGLUtils.h
  libs/openFrameworks/gl/ofTexture.h
  libs/openFrameworks/utils/ofConstants.h
  libs/openFrameworksCompiled/project/ios/iOS+OFLib.xcodeproj/project.pbxproj
  libs/openFrameworksCompiled/project/tvOS/tvOS+OFLib.xcodeproj/project.pbxproj
Labels: iOS

#8095 Adding support for OF_KEY_SPACE - @Makio135 #5592
  libs/openFrameworks/app/ofAppEGLWindow.cpp
  libs/openFrameworks/app/ofAppGLFWWindow.cpp
  libs/openFrameworks/events/ofEvents.h
Labels: input

#5145 add ofBoundingBox
  libs/openFrameworks/3d/of3dPrimitives.cpp
  libs/openFrameworks/3d/of3dPrimitives.h
  libs/openFrameworks/graphics/ofGraphicsBaseTypes.h
Labels: section-3D

#6137 Add PUT request to ofURLFileLoader
  libs/openFrameworks/utils/ofURLFileLoader.cpp
  libs/openFrameworks/utils/ofURLFileLoader.h
Labels: bitesize
