Repository openframeworks/openFrameworks, pull requests merged in 2025-03, with the labels that each got.

#8341 Android - script updates for download_libs
  scripts/android/download_libs.sh
  scripts/dev/download_libs.sh
  scripts/of.sh
Labels: android, scripts

#8372 ofURLFileLoader Windows
  libs/openFrameworks/utils/ofURLFileLoader.cpp
Labels: visual studio

#8373 Nightly - Android - Linux
  .github/workflows/nightly.yml
  scripts/ci/package_builds.sh
  scripts/dev/create_package.sh
  scripts/dev/download_libs.sh
Labels: automation

#8376 Android Updates / Nightly / Docs
  .github/workflows/nightly.yml
  .github/workflows/of.yml
  docs/android_studio.md
  libs/openFrameworksCompiled/project/android/common-functions.gradle
  scripts/dev/create_package.sh
  scripts/templates/android2024/ofApp/build.gradle
  scripts/templates/android2024/ofApp/src/main/cpp/CMakeLists.txt
Labels: android

#8393 ofxAssimp: Convert animation mixer animation clip references to weak_ptrs
  addons/ofxAssimp/src/ofxAssimpAnimationMixer.cpp
  addons/ofxAssimp/src/ofxAssimpAnimationMixer.h
  addons/ofxAssimp/src/ofxAssimpNode.cpp
  addons/ofxAssimp/src/ofxAssimpScene.cpp
  addons/ofxAssimp/src/ofxAssimpScene.h
Labels: addon

#8384 cURL / OpenSSL core api fixes
  libs/openFrameworks/graphics/ofImage.cpp
  libs/openFrameworks/utils/ofURLFileLoader.cpp
  libs/openFrameworks/utils/ofURLFileLoader.h
Labels: bug

#8399 ofCubeMap: Android define around regenerateAllTextures()
  libs/openFrameworks/gl/ofCubeMap.cpp
  libs/openFrameworks/gl/ofCubeMap.h
  libs/openFrameworks/gl/ofCubeMapShaders.h
Labels: bug, bitesize, android
